name: first workflow
on:
  workflow_dispatch:
  pull_request:
  push:
      
jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: current GitHub Actions workflow repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: track changed files
        shell: bash
        run: |
          mkdir Code_Guru
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -v -e "tests/.*" | xargs -I {} sh -c 'cp {} "Code_Guru/$(echo {} | tr '/' '-' )"'
          ls Code_Guru/
          

      
