name: CodeGuru Scan

on:
  pull_request:
    branches: [main]
      
jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: current GitHub Actions workflow repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: track changed files
        shell: bash
        run: |
          mkdir Code_Guru
          CG=$(git diff --diff-filter=dr --name-only -r HEAD^1 HEAD) 
          for file in ${{vars.EXCLUDE_CODEGURU_SCAN}};
            do exclude="${exclude} -e ${file}"
          done
          echo "$CG" | if [[ ${{ vars.EXCLUDE_CODEGURU_SCAN }} ]]; then grep -v $exclude; fi | xargs -I {} sh -c 'cp {} "Code_Guru/$(echo {} | tr '/' '-' )"' 

      - name: codeguru scan 
        run: |
          echo -e "Files scanned by codeguru :\n$(ls Code_Guru/) "
          echo -e "Files excluded by codeguru : ${{vars.EXCLUDE_CODEGURU_SCAN}}"
          
          

      
