name: CodeGuru Scan

on:
  pull_request:
    branches: [main]
      
jobs: 
  first_job:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: current GitHub Actions workflow repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: track changed files 
        shell: bash
        run: |
          mkdir Code_Guru
          for file in ${{vars.EXCLUDE_CODEGURU_SCAN}};
            do exclude="${exclude} -e ${file}"
          done
          git diff --diff-filter=dr --name-only -r HEAD^1 HEAD | grep -v $exclude | xargs -I {} sh -c 'cp {} "Code_Guru/$(echo {} | tr '/' '-' )"' 
          echo -e "Files scanned by codeguru :\n$(ls Code_Guru/) "
          echo "hello world"
          
          

      
